/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initiate Google OAuth flow */
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback */
        get: operations["AuthController_googleAuthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/facebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initiate Facebook OAuth flow */
        get: operations["AuthController_facebookAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/facebook/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facebook OAuth callback */
        get: operations["AuthController_facebookAuthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user with email and password */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password for authenticated user */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users (Admin only) */
        get: operations["AuthController_getAllUsers"];
        put?: never;
        /** Create a new user (Admin only) */
        post: operations["AuthController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID (Admin only) */
        get: operations["AuthController_getUserById"];
        /** Update user by ID (Admin only) */
        put: operations["AuthController_updateUser"];
        post?: never;
        /** Delete user by ID (Admin only) */
        delete: operations["AuthController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated audit logs (Admin only) */
        get: operations["AuditLogController_getAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs/stats/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get action statistics for a specific user */
        get: operations["AuditLogController_getUserActionStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs/errors/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent error logs */
        get: operations["AuditLogController_getRecentErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get audit log by ID */
        get: operations["AuditLogController_getLogById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all business settings (Admin: all, Tenant: own) */
        get: operations["BusinessSettingsController_findAll"];
        put?: never;
        /** Create business settings (Tenant only) */
        post: operations["BusinessSettingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/business-settings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get business settings by ID */
        get: operations["BusinessSettingsController_findOne"];
        /** Update business settings */
        put: operations["BusinessSettingsController_update"];
        post?: never;
        /** Delete business settings */
        delete: operations["BusinessSettingsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all interventions (Admin: all, Tenant: own) */
        get: operations["InterventionController_findAll"];
        put?: never;
        /** Create intervention/service (Tenant only) */
        post: operations["InterventionController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interventions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get intervention by ID */
        get: operations["InterventionController_findOne"];
        /** Update intervention */
        put: operations["InterventionController_update"];
        post?: never;
        /** Delete intervention */
        delete: operations["InterventionController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all masters (Admin: all, Tenant: own) */
        get: operations["MasterController_findAll"];
        put?: never;
        /** Create master (Tenant only) */
        post: operations["MasterController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/masters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get master by ID */
        get: operations["MasterController_findOne"];
        /** Update master */
        put: operations["MasterController_update"];
        post?: never;
        /** Delete master */
        delete: operations["MasterController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User password (min 8 chars, must contain uppercase, lowercase, and number/special char)
             * @example SecurePassword123!
             */
            password: string;
            /**
             * @description User first name
             * @example John
             */
            firstName: string;
            /**
             * @description User last name
             * @example Doe
             */
            lastName: string;
        };
        AuthResponseDto: {
            /**
             * @description JWT access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token: string;
        };
        LoginDto: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User password
             * @example SecurePassword123!
             */
            password: string;
        };
        ForgotPasswordDto: {
            /**
             * @description Email address to send password reset instructions
             * @example user@example.com
             */
            email: string;
        };
        MessageResponseDto: {
            /**
             * @description Response message
             * @example Operation completed successfully
             */
            message: string;
        };
        ResetPasswordDto: {
            /**
             * @description Password reset token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token: string;
            /**
             * @description New password (min 8 chars, must contain uppercase, lowercase, and number/special char)
             * @example NewSecurePassword123!
             */
            newPassword: string;
        };
        ChangePasswordDto: {
            /**
             * @description Current password
             * @example OldPassword123!
             */
            currentPassword: string;
            /**
             * @description New password (min 8 chars, must contain uppercase, lowercase, and number/special char)
             * @example NewSecurePassword123!
             */
            newPassword: string;
        };
        UserDto: {
            /**
             * @description User unique identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User first name
             * @example John
             */
            firstName: string;
            /**
             * @description User last name
             * @example Doe
             */
            lastName: string;
            /**
             * @description User avatar URL
             * @example https://example.com/avatar.jpg
             */
            avatar?: string;
            /**
             * @description User role
             * @example client
             * @enum {string}
             */
            role: "admin" | "tenant" | "client";
        };
        CreateUserDto: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User password (optional for OAuth users)
             * @example SecurePassword123!
             */
            password?: string;
            /**
             * @description User first name
             * @example John
             */
            firstName: string;
            /**
             * @description User last name
             * @example Doe
             */
            lastName: string;
            /**
             * @description User avatar URL
             * @example https://example.com/avatar.jpg
             */
            avatar?: string;
            /**
             * @description User role
             * @example client
             * @enum {string}
             */
            role?: "admin" | "tenant" | "client";
            /**
             * @description Authentication provider
             * @example local
             * @enum {string}
             */
            authProvider?: "google" | "facebook" | "local";
            /**
             * @description OAuth provider user ID
             * @example 1234567890
             */
            providerId?: string;
            /**
             * @description Whether the user account is active
             * @example true
             */
            isActive?: boolean;
        };
        UpdateUserDto: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email?: string;
            /**
             * @description User first name
             * @example John
             */
            firstName?: string;
            /**
             * @description User last name
             * @example Doe
             */
            lastName?: string;
            /**
             * @description User avatar URL
             * @example https://example.com/avatar.jpg
             */
            avatar?: string;
            /**
             * @description User role
             * @example client
             * @enum {string}
             */
            role?: "admin" | "tenant" | "client";
            /**
             * @description Whether the user account is active
             * @example true
             */
            isActive?: boolean;
        };
        WorkingHoursDto: {
            /**
             * @description Day of the week
             * @example Monday
             */
            day: string;
            /**
             * @description Opening time
             * @example 09:00
             */
            openTime: string;
            /**
             * @description Closing time
             * @example 18:00
             */
            closeTime: string;
            /**
             * @description Whether the business is closed on this day
             * @example false
             */
            isClosed?: boolean;
        };
        SocialLinksDto: {
            /**
             * @description Facebook URL
             * @example https://facebook.com/business
             */
            facebook?: string;
            /**
             * @description Instagram URL
             * @example https://instagram.com/business
             */
            instagram?: string;
            /**
             * @description Twitter URL
             * @example https://twitter.com/business
             */
            twitter?: string;
            /**
             * @description LinkedIn URL
             * @example https://linkedin.com/company/business
             */
            linkedin?: string;
            /**
             * @description Website URL
             * @example https://business.com
             */
            website?: string;
        };
        CreateBusinessSettingsDto: {
            /**
             * @description Business title
             * @example Beauty Salon & Spa
             */
            title: string;
            /**
             * @description Business description
             * @example Professional beauty services in the heart of the city
             */
            description?: string;
            /**
             * @description Business address
             * @example 123 Main Street, Warsaw, Poland
             */
            address?: string;
            /**
             * @description Working hours for each day of the week
             * @example [
             *       {
             *         "day": "Monday",
             *         "openTime": "09:00",
             *         "closeTime": "18:00",
             *         "isClosed": false
             *       },
             *       {
             *         "day": "Tuesday",
             *         "openTime": "09:00",
             *         "closeTime": "18:00",
             *         "isClosed": false
             *       }
             *     ]
             */
            workingHours: components["schemas"]["WorkingHoursDto"][];
            /**
             * @description Google Calendar integration ID
             * @example calendar@example.com
             */
            googleCalendarId?: string;
            /** @description Social media links */
            socialLinks?: components["schemas"]["SocialLinksDto"];
        };
        BusinessSettingsDto: {
            /**
             * @description Business settings unique identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Tenant user ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            userId: string;
            /**
             * @description Business title
             * @example Beauty Salon & Spa
             */
            title: string;
            /**
             * @description Business description
             * @example Professional beauty services in the heart of the city
             */
            description?: string;
            /**
             * @description Business address
             * @example 123 Main Street, Warsaw, Poland
             */
            address?: string;
            /** @description Working hours for each day of the week */
            workingHours: components["schemas"]["WorkingHoursDto"][];
            /**
             * @description Google Calendar integration ID
             * @example calendar@example.com
             */
            googleCalendarId?: string;
            /** @description Social media links */
            socialLinks?: components["schemas"]["SocialLinksDto"];
        };
        UpdateBusinessSettingsDto: {
            /**
             * @description Business title
             * @example Beauty Salon & Spa
             */
            title?: string;
            /**
             * @description Business description
             * @example Professional beauty services in the heart of the city
             */
            description?: string;
            /**
             * @description Business address
             * @example 123 Main Street, Warsaw, Poland
             */
            address?: string;
            /** @description Working hours for each day of the week */
            workingHours?: components["schemas"]["WorkingHoursDto"][];
            /**
             * @description Google Calendar integration ID
             * @example calendar@example.com
             */
            googleCalendarId?: string;
            /** @description Social media links */
            socialLinks?: components["schemas"]["SocialLinksDto"];
        };
        CreateInterventionDto: {
            /**
             * @description Intervention/service name
             * @example Classic Manicure
             */
            name: string;
            /**
             * @description Price of the service
             * @example 50
             */
            price: number;
            /**
             * @description Currency
             * @default PLN
             * @example PLN
             * @enum {string}
             */
            currency: "PLN" | "USD" | "EUR" | "GBP";
            /**
             * @description Service images URLs
             * @example [
             *       "https://example.com/image1.jpg",
             *       "https://example.com/image2.jpg"
             *     ]
             */
            images?: string[];
            /**
             * @description Duration of the service in minutes
             * @example 60
             */
            duration: number;
            /**
             * @description Service description
             * @example Professional manicure with nail polish of your choice
             */
            description?: string;
            /**
             * @description Array of master IDs who can perform this service
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            masterIds?: string[];
        };
        InterventionDto: {
            /**
             * @description Intervention unique identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Business settings ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            businessSettingsId: string;
            /**
             * @description Intervention/service name
             * @example Classic Manicure
             */
            name: string;
            /**
             * @description Price of the service
             * @example 50
             */
            price: number;
            /**
             * @description Currency
             * @example PLN
             * @enum {string}
             */
            currency: "PLN" | "USD" | "EUR" | "GBP";
            /**
             * @description Service images URLs
             * @example [
             *       "https://example.com/image1.jpg",
             *       "https://example.com/image2.jpg"
             *     ]
             */
            images?: string[];
            /**
             * @description Duration of the service in minutes
             * @example 60
             */
            duration: number;
            /**
             * @description Service description
             * @example Professional manicure with nail polish of your choice
             */
            description?: string;
        };
        UpdateInterventionDto: {
            /**
             * @description Intervention/service name
             * @example Classic Manicure
             */
            name?: string;
            /**
             * @description Price of the service
             * @example 50
             */
            price?: number;
            /**
             * @description Currency
             * @example PLN
             * @enum {string}
             */
            currency?: "PLN" | "USD" | "EUR" | "GBP";
            /**
             * @description Service images URLs
             * @example [
             *       "https://example.com/image1.jpg",
             *       "https://example.com/image2.jpg"
             *     ]
             */
            images?: string[];
            /**
             * @description Duration of the service in minutes
             * @example 60
             */
            duration?: number;
            /**
             * @description Service description
             * @example Professional manicure with nail polish of your choice
             */
            description?: string;
            /**
             * @description Array of master IDs who can perform this service
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            masterIds?: string[];
        };
        CreateMasterDto: {
            /**
             * @description Master name
             * @example Anna Kowalska
             */
            name: string;
            /**
             * @description Master date of birth
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description Master photo URL
             * @example https://example.com/masters/anna.jpg
             */
            photo?: string;
            /**
             * @description Master description/bio
             * @example Experienced nail technician with 10+ years of experience
             */
            description?: string;
        };
        MasterDto: {
            /**
             * @description Master unique identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Business settings ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            businessSettingsId: string;
            /**
             * @description Master name
             * @example Anna Kowalska
             */
            name: string;
            /**
             * @description Master date of birth
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description Master photo URL
             * @example https://example.com/masters/anna.jpg
             */
            photo?: string;
            /**
             * @description Master description/bio
             * @example Experienced nail technician with 10+ years of experience
             */
            description?: string;
        };
        UpdateMasterDto: {
            /**
             * @description Master name
             * @example Anna Kowalska
             */
            name?: string;
            /**
             * @description Master date of birth
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description Master photo URL
             * @example https://example.com/masters/anna.jpg
             */
            photo?: string;
            /**
             * @description Master description/bio
             * @example Experienced nail technician with 10+ years of experience
             */
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to Google OAuth */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuthCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to frontend with JWT token */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_facebookAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to Facebook OAuth */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_facebookAuthCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to frontend with JWT token */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully, returns JWT token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful, returns JWT token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset instructions sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Invalid or expired reset token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Invalid current password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns list of all users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_getAuditLogs: {
        parameters: {
            query?: {
                /** @description Filter by action type */
                action?: "login" | "logout" | "register" | "password_change" | "password_reset" | "user_create" | "user_update" | "user_delete" | "profile_update" | "api_request" | "error";
                /** @description Filter by user ID */
                userId?: string;
                /** @description Filter by entity name */
                entity?: string;
                /** @description Filter by start date (ISO 8601 format) */
                startDate?: string;
                /** @description Filter by end date (ISO 8601 format) */
                endDate?: string;
                /** @description Page number for pagination */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns paginated audit logs with metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_getUserActionStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns action statistics grouped by action type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_getRecentErrors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the 20 most recent error logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_getLogById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audit log ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns audit log details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Audit log not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessSettingsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns list of business settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSettingsDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessSettingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBusinessSettingsDto"];
            };
        };
        responses: {
            /** @description Business settings created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSettingsDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessSettingsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Business settings ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns business settings details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSettingsDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Business settings not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessSettingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Business settings ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBusinessSettingsDto"];
            };
        };
        responses: {
            /** @description Business settings updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessSettingsDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Business settings not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BusinessSettingsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Business settings ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Business settings deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Business settings not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InterventionController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns list of interventions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InterventionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInterventionDto"];
            };
        };
        responses: {
            /** @description Intervention created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InterventionController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Intervention ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns intervention details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Intervention not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InterventionController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Intervention ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInterventionDto"];
            };
        };
        responses: {
            /** @description Intervention updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Intervention not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InterventionController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Intervention ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intervention deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Intervention not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MasterController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns list of masters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MasterController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMasterDto"];
            };
        };
        responses: {
            /** @description Master created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MasterController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Master ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns master details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Master not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MasterController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Master ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMasterDto"];
            };
        };
        responses: {
            /** @description Master updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasterDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Master not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MasterController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Master ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Master deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Master not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
