/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantTenantIdIndexRouteImport } from './routes/tenant/$tenantId/index'
import { Route as TenantTenantIdBookRouteImport } from './routes/tenant/$tenantId/book'

const UsersLazyRouteImport = createFileRoute('/users')()
const BusinessSettingsLazyRouteImport = createFileRoute('/business-settings')()
const ActionsLazyRouteImport = createFileRoute('/actions')()
const IndexLazyRouteImport = createFileRoute('/')()
const AuthResetPasswordLazyRouteImport = createFileRoute(
  '/auth/reset-password',
)()
const AuthCallbackLazyRouteImport = createFileRoute('/auth/callback')()

const UsersLazyRoute = UsersLazyRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/users.lazy').then((d) => d.Route))
const BusinessSettingsLazyRoute = BusinessSettingsLazyRouteImport.update({
  id: '/business-settings',
  path: '/business-settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/business-settings.lazy').then((d) => d.Route),
)
const ActionsLazyRoute = ActionsLazyRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/actions.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AuthResetPasswordLazyRoute = AuthResetPasswordLazyRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/reset-password.lazy').then((d) => d.Route),
)
const AuthCallbackLazyRoute = AuthCallbackLazyRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/callback.lazy').then((d) => d.Route))
const TenantTenantIdIndexRoute = TenantTenantIdIndexRouteImport.update({
  id: '/tenant/$tenantId/',
  path: '/tenant/$tenantId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantTenantIdBookRoute = TenantTenantIdBookRouteImport.update({
  id: '/tenant/$tenantId/book',
  path: '/tenant/$tenantId/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/actions': typeof ActionsLazyRoute
  '/business-settings': typeof BusinessSettingsLazyRoute
  '/users': typeof UsersLazyRoute
  '/auth/callback': typeof AuthCallbackLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/tenant/$tenantId/book': typeof TenantTenantIdBookRoute
  '/tenant/$tenantId': typeof TenantTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/actions': typeof ActionsLazyRoute
  '/business-settings': typeof BusinessSettingsLazyRoute
  '/users': typeof UsersLazyRoute
  '/auth/callback': typeof AuthCallbackLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/tenant/$tenantId/book': typeof TenantTenantIdBookRoute
  '/tenant/$tenantId': typeof TenantTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/actions': typeof ActionsLazyRoute
  '/business-settings': typeof BusinessSettingsLazyRoute
  '/users': typeof UsersLazyRoute
  '/auth/callback': typeof AuthCallbackLazyRoute
  '/auth/reset-password': typeof AuthResetPasswordLazyRoute
  '/tenant/$tenantId/book': typeof TenantTenantIdBookRoute
  '/tenant/$tenantId/': typeof TenantTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/business-settings'
    | '/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/tenant/$tenantId/book'
    | '/tenant/$tenantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/business-settings'
    | '/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/tenant/$tenantId/book'
    | '/tenant/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/business-settings'
    | '/users'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/tenant/$tenantId/book'
    | '/tenant/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ActionsLazyRoute: typeof ActionsLazyRoute
  BusinessSettingsLazyRoute: typeof BusinessSettingsLazyRoute
  UsersLazyRoute: typeof UsersLazyRoute
  AuthCallbackLazyRoute: typeof AuthCallbackLazyRoute
  AuthResetPasswordLazyRoute: typeof AuthResetPasswordLazyRoute
  TenantTenantIdBookRoute: typeof TenantTenantIdBookRoute
  TenantTenantIdIndexRoute: typeof TenantTenantIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-settings': {
      id: '/business-settings'
      path: '/business-settings'
      fullPath: '/business-settings'
      preLoaderRoute: typeof BusinessSettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$tenantId/': {
      id: '/tenant/$tenantId/'
      path: '/tenant/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof TenantTenantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$tenantId/book': {
      id: '/tenant/$tenantId/book'
      path: '/tenant/$tenantId/book'
      fullPath: '/tenant/$tenantId/book'
      preLoaderRoute: typeof TenantTenantIdBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ActionsLazyRoute: ActionsLazyRoute,
  BusinessSettingsLazyRoute: BusinessSettingsLazyRoute,
  UsersLazyRoute: UsersLazyRoute,
  AuthCallbackLazyRoute: AuthCallbackLazyRoute,
  AuthResetPasswordLazyRoute: AuthResetPasswordLazyRoute,
  TenantTenantIdBookRoute: TenantTenantIdBookRoute,
  TenantTenantIdIndexRoute: TenantTenantIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
